apiVersion: v1
data:
  # upload.sh: "#/bin/sh\n\n# create /backup folder and put files there\n\n\n# # Check
  #   if the backup files exist or empty\n# ls -trl /backup\n# #CONSUL_BACKUP_FILE=/backup/$(ls
  #   /backup|grep consul)\n# #if [ -f \"$VAULT_BACKUP_FILE\" ] && [ -f \"$CONSUL_BACKUP_FILE\"
  #   ] && [ ! -s \"$VAULT_BACKUP_FILE\" ] && [ ! -s \"$CONSUL_BACKUP_FILE\" ]; then
  #   echo \"Files $VAULT_BACKUP_FILE and $CONSUL_BACKUP_FILE exist but have size 0\"
  #   && exit 1; elif [ -f \"$VAULT_BACKUP_FILE\" ] && [ -f \"$CONSUL_BACKUP_FILE\"
  #   ]; then echo \"Files $VAULT_BACKUP_FILE and $CONSUL_BACKUP_FILE exist and have
  #   size greater than 0\"; else echo \"One or both of the files $VAULT_BACKUP_FILE
  #   and $CONSUL_BACKUP_FILE do not exist\" && exit 2; fi \n\n# VAULT_BACKUP_FILE=/backup/$(ls
  #   /backup|grep vault)\n# if [ -f \"$VAULT_BACKUP_FILE\" ] && [ -s \"$VAULT_BACKUP_FILE\"
  #   ]  \n# then \n#     echo \"$VAULT_BACKUP_FILE exists! Backing up now...\" \n#
  #   else \n#     echo \"Backup fails! Either the file doesn't exist or it is empty.
  #   Please check your script!\" && exit 2\n# fi\n\n# Copy backup files to minio object
  #   storage\nmc alias set local-minio http://$MINIO_ADDR:9000 $MINIO_USERNAME $MINIO_PASSWORD\n#
  #   mc cp --recursive /backup/* local-minio/$BUCKET_NAME\nmc cp --recursive /* local-minio/$BUCKET_NAME\n"
  upload.sh: |-
    #/bin/sh
    mc alias set local-minio http://$MINIO_ADDR:9000 $MINIO_USERNAME $MINIO_PASSWORD
    mc cp --recursive /* local-minio/$BUCKET_NAME
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: upload
  namespace: vault-test
